name: Deploy Project

on:
  push:
    branches: 
      - main
      - test   # PR 전 test 브랜치에서 동작되는지 확인
  pull_request:
    branches: 
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      backend: ./WAGGLE_BACKEND
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
        working-directory: ${{ env.backend }}

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle
        working-directory: ${{ env.backend }}

      - name: Gradle execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: ${{ env.backend }}

      - name: Build with Gradle
        run: ./gradlew clean build
        working-directory: ${{ env.backend }}
      
      - name: Separate of Spring application layers
        run: java -Djarmode=layertools -jar build/libs/${{ secrets.JAR_NAME }} extract
        working-directory: ${{ env.backend }}
