name: Deploy Project

on:
  push:
    branches: 
      - main
      - test   # PR 전 test 브랜치에서 동작되는지 확인
  pull_request:
    branches: 
      - main
  workflow_dispatch:

permissions:
  content: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Backend Deploy
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runnder.os }}-gradle

      - name: Gradle execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      
      - name: Separate of Spring application layers
        run: java -Djarmode=layertools -jar build/libs/${{ secrets.JAR_NAME }} extract