name: Deploy Frontend Project

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./WAGGLE_WEB_FRONTEND
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      